"""Check whether the event-camera corruptions actually degrade the detector's mAP.

This is the analysis-side CHECK for the motivation experiment. The *model run* is
`HybridDetection/validation_corrupt.py` (it feeds clean vs corrupted event input
through the pretrained Hybrid detector and logs Prophesee COCO mAP to
`results/neftci_map_degradation.csv`); this script consumes that CSV and answers:

  1. Does each corruption reduce mAP versus the clean baseline, and by how much?
  2. Is the drop monotone in severity (a well-behaved corruption)?
  3. Does mAP damage line up with OOD-detectability? — i.e. are the corruptions that
     hurt the model the ones the φ detector (MDD) catches? (the paper's core link)

It writes a verdict table + a tidy summary CSV. The paper figures built from this CSV
(28_map_degradation.png, 29_map_drop_vs_detectability.png) are generated by
analysis/plot_corruption_graphs.py, the single figure generator for the paper.

If the mAP CSV does not exist yet it prints exactly how to generate it and exits 0.

Run:  python analysis/check_map_degradation.py
"""
import sys
from pathlib import Path
import numpy as np
import pandas as pd

_HERE = Path(__file__).resolve().parent
REPO = _HERE.parent
_RES = REPO / "vmem_benchmark" / "outputs" / "results"
MAP_CSV = _RES / "neftci_map_degradation.csv"
SUMMARY = _RES / "neftci_map_degradation_summary.csv"

CORRS = ["hot_pixel", "event_flood", "temporal_jitter",
         "event_rate_shift", "polarity_flip", "spatial_dropout"]
REL_DROP_SIGNIF = 5.0   # >5% relative mAP loss counts as "degrades"


def _how_to_generate():
    print(f"[check_map_degradation] {MAP_CSV} not found — the detector sweep hasn't run yet.\n")
    print("Generate it (runs the pretrained detector on clean + the 6x5 grid; needs the")
    print("HybridDetection env + GPU + Gen1 test split):\n")
    print("    cd HybridDetection")
    print("    GPU_ID=0 USE_TEST_SET=true sh run_map_degradation.sh        # full sweep")
    print("    SMOKE=1 sh run_map_degradation.sh                           # quick pipeline check\n")
    print("Then re-run:  python analysis/summarize_map_degradation.py  &&  python analysis/check_map_degradation.py")


def load_map():
    df = pd.read_csv(MAP_CSV)
    df = df.drop_duplicates(subset=["corruption", "severity"], keep="last")
    clean = df[df.corruption.isin(["clean", "none"])]
    if clean.empty:
        raise SystemExit("no clean baseline row in the CSV — run the `+corruption=clean` case.")
    clean_ap = float(clean.AP.iloc[0]); clean_ap50 = float(clean.AP_50.iloc[0])
    rows = df[~df.corruption.isin(["clean", "none"])].copy()
    rows["mAP_drop"] = clean_ap - rows.AP
    rows["rel_drop_pct"] = 100.0 * rows.mAP_drop / clean_ap if clean_ap else np.nan
    rows["AP50_drop"] = clean_ap50 - rows.AP_50
    rows["degraded"] = rows.rel_drop_pct > REL_DROP_SIGNIF
    return rows, clean_ap, clean_ap50


def verdict(rows, clean_ap):
    present = [c for c in CORRS if c in set(rows.corruption)]
    print(f"\nClean baseline mAP = {clean_ap:.4f}\n")
    hdr = f"  {'corruption':<18} {'sev->mAP (drop%)':<46} {'monotone?':<10} {'degrades?'}"
    print(hdr); print("  " + "-" * (len(hdr) - 2))
    n_deg = 0
    for c in present:
        d = rows[rows.corruption == c].sort_values("severity")
        cells = "  ".join(f"L{int(s)}:{ap:.3f}(-{rd:.0f}%)" for s, ap, rd in
                          zip(d.severity, d.AP, d.rel_drop_pct))
        # monotone decreasing in severity (Spearman ρ < 0, |ρ| high)
        mono = "yes" if (len(d) >= 3 and np.corrcoef(d.severity, d.AP)[0, 1] < -0.5) else "—"
        deg = bool(d.degraded.any())
        n_deg += deg
        print(f"  {c:<18} {cells:<46} {mono:<10} {'YES' if deg else 'no'}")
    print(f"\n  => {n_deg}/{len(present)} corruptions significantly reduce mAP "
          f"(>{REL_DROP_SIGNIF:.0f}% relative at some severity).")
    worst = rows.loc[rows.mAP_drop.idxmax()]
    print(f"  => largest damage: {worst.corruption} L{int(worst.severity)} "
          f"mAP {worst.AP:.3f} (-{worst.mAP_drop:.3f}, -{worst.rel_drop_pct:.0f}%)")



def _parse_args():
    import argparse
    ap = argparse.ArgumentParser(description="Check detector mAP degradation under corruption.")
    ap.add_argument("--map-csv", default=str(MAP_CSV),
                    help="mAP CSV from validation_corrupt.py (default: results/neftci_map_degradation.csv)")
    ap.add_argument("--output-dir", default=None,
                    help="dir for the summary CSV (default: results/)")
    return ap.parse_args()


def main():
    global MAP_CSV, SUMMARY
    args = _parse_args()
    MAP_CSV = Path(args.map_csv)
    if args.output_dir:
        out = Path(args.output_dir)
        SUMMARY = out / "neftci_map_degradation_summary.csv"
    if not MAP_CSV.exists():
        _how_to_generate(); return
    rows, clean_ap, clean_ap50 = load_map()
    verdict(rows, clean_ap)
    SUMMARY.parent.mkdir(parents=True, exist_ok=True)
    cols = ["corruption", "severity", "AP", "AP_50", "mAP_drop", "rel_drop_pct", "AP50_drop", "degraded"]
    rows.sort_values(["corruption", "severity"])[cols].to_csv(SUMMARY, index=False)
    print(f"\nwrote {SUMMARY}")
    print("(figures 28/29 are generated by analysis/plot_corruption_graphs.py from this CSV)")


if __name__ == "__main__":
    main()
